name: labeler
on:
  issues: 
    types: [opened, edited, reopened]
  pull_request:
    types: [opened, edited, reopened, ready_for_review, synchronize]

jobs:
  labeler:
    runs-on: ubuntu-latest
    name: label issues and pull requests
    steps:
      - name: check-out-repository
        uses: actions/checkout@v2

      - name: labeler
        uses: IvanFon/super-labeler-action@@master
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'

      - name: pr-labeler-size
        if: github.event_name == 'pull_request'
        uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_max_size: '10'
          s_max_size: '100'
          m_max_size: '500'
          l_max_size: '1000'
          fail_if_xl: 'false'